name: CI devops 2024
on:
  # lancer le job dans les branches main et develop
  push:
    branches:
      - main
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # checkout du code GitHub
      - uses: actions/checkout@v2.5.0

      # configuration de JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # construction et tests avec Maven
      - name: Build and test with Maven
        run: mvn clean verify --file simple-api/pom.xml
